"""initial

Revision ID: ab1b782a7229
Revises: 
Create Date: 2026-06-25 13:14:46.080882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ab1b782a7229'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'id',
               existing_type=mysql.INTEGER(unsigned=True),
               comment=None,
               existing_comment='书籍ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('books', 'title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment=None,
               existing_comment='书名',
               existing_nullable=False)
    op.alter_column('books', 'author',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               server_default=None,
               comment=None,
               existing_comment='作者',
               existing_nullable=True)
    op.alter_column('books', 'cover',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               server_default=None,
               comment=None,
               existing_comment='封面图片URL',
               existing_nullable=True)
    op.alter_column('books', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.drop_table_comment(
        'books',
        existing_comment='书籍表',
        schema=None
    )
    op.drop_table_comment(
        'excerpt_tags',
        existing_comment='摘抄标签关联表',
        schema=None
    )
    op.alter_column('excerpts', 'id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment=None,
               existing_comment='摘抄ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('excerpts', 'book_id',
               existing_type=mysql.INTEGER(unsigned=True),
               comment=None,
               existing_comment='所属书籍',
               existing_nullable=False)
    op.alter_column('excerpts', 'content',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='摘抄原文',
               existing_nullable=True)
    op.alter_column('excerpts', 'insights',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='个人想法/评论',
               existing_nullable=True)
    op.alter_column('excerpts', 'links',
               existing_type=mysql.JSON(),
               server_default=None,
               comment=None,
               existing_comment='链接数组',
               existing_nullable=True)
    op.alter_column('excerpts', 'images',
               existing_type=mysql.JSON(),
               server_default=None,
               comment=None,
               existing_comment='图片URL数组',
               existing_nullable=True)
    op.alter_column('excerpts', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('excerpts', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.drop_index(op.f('ft_excerpt'), table_name='excerpts', mysql_prefix='FULLTEXT', mysql_with_parser='ngram')
    op.drop_table_comment(
        'excerpts',
        existing_comment='摘抄主表',
        schema=None
    )
    op.alter_column('tags', 'id',
               existing_type=mysql.INTEGER(unsigned=True),
               comment=None,
               existing_comment='标签ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('tags', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='标签名',
               existing_nullable=False)
    op.alter_column('tags', 'color',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=7),
               server_default=None,
               comment=None,
               existing_comment='标签颜色(hex)',
               existing_nullable=True)
    op.alter_column('tags', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.drop_table_comment(
        'tags',
        existing_comment='标签表',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'tags',
        '标签表',
        existing_comment=None,
        schema=None
    )
    op.alter_column('tags', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('tags', 'color',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=7),
               server_default=sa.text("'#409EFF'"),
               comment='标签颜色(hex)',
               existing_nullable=True)
    op.alter_column('tags', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='标签名',
               existing_nullable=False)
    op.alter_column('tags', 'id',
               existing_type=mysql.INTEGER(unsigned=True),
               comment='标签ID',
               existing_nullable=False,
               autoincrement=True)
    op.create_table_comment(
        'excerpts',
        '摘抄主表',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('ft_excerpt'), 'excerpts', ['content', 'insights'], unique=False, mysql_prefix='FULLTEXT', mysql_with_parser='ngram')
    op.alter_column('excerpts', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('excerpts', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('excerpts', 'images',
               existing_type=mysql.JSON(),
               server_default=sa.text('(json_array())'),
               comment='图片URL数组',
               existing_nullable=True)
    op.alter_column('excerpts', 'links',
               existing_type=mysql.JSON(),
               server_default=sa.text('(json_array())'),
               comment='链接数组',
               existing_nullable=True)
    op.alter_column('excerpts', 'insights',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='个人想法/评论',
               existing_nullable=True)
    op.alter_column('excerpts', 'content',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='摘抄原文',
               existing_nullable=True)
    op.alter_column('excerpts', 'book_id',
               existing_type=mysql.INTEGER(unsigned=True),
               comment='所属书籍',
               existing_nullable=False)
    op.alter_column('excerpts', 'id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='摘抄ID',
               existing_nullable=False,
               autoincrement=True)
    op.create_table_comment(
        'excerpt_tags',
        '摘抄标签关联表',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'books',
        '书籍表',
        existing_comment=None,
        schema=None
    )
    op.alter_column('books', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('books', 'cover',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               server_default=sa.text("''"),
               comment='封面图片URL',
               existing_nullable=True)
    op.alter_column('books', 'author',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               server_default=sa.text("''"),
               comment='作者',
               existing_nullable=True)
    op.alter_column('books', 'title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment='书名',
               existing_nullable=False)
    op.alter_column('books', 'id',
               existing_type=mysql.INTEGER(unsigned=True),
               comment='书籍ID',
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
